version: "3.9"

services:
  app:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=localhost
      - DB_NAME=testdb
      - DB_USER=postgres
      - DB_PASSWORD=Bsk2%40stage

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Bsk2%40stage
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
