services:
  - type: web
    name: fastapi-event-triggers
    runtime: docker
    region: oregon
    repo: https://github.com/vishal-n/event_trigger_management_app
    branch: master
    dockerfilePath: ./Dockerfile
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.event_triggers_app:app --host 0.0.0.0 --port 10000
    envVars:
      - key: DATABASE_URL
        sync: false